name: lab10
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^1.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
      - assets/images/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: ./assets/fonts/RobotoMono-VariableFont_wght.ttf
  
    - family: PoetsenOne
      fonts:
        - asset: ./assets/fonts/PoetsenOne-Regular.ttf
  
    - family: BebasNeue
      fonts:
        - asset: ./assets/fonts/BebasNeue-Regular.ttf

  uses-material-design: true
  